name: Output information
on: workflow_dispatch
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details on issues
        run: echo " ${{ toJSON(github.event) }}"
